### ISSUE TITLE
error:Model is created with a newer version(R2020a) of Simulink

### ISSUE THREAD

**Issue by jiang-jian-yu** [vishal-codes/FOPID-tuner-using-GA#1]
Please give me a hand.The method is load the model in Simulink R2020a and select Save>Export Model to >Previous Version.

**Comment by gyani-codes** [comment]
Can you add a screenshot ?

**Comment by jiang-jian-yu** [comment]
Thanks for your reply.I have installed MATLAB(2020a),and the problem is solved.Thanks for your's project again.

**Comment by jiang-jian-yu** [comment]
> Can you add a screenshot ?
Thanks for your reply.I have installed MATLAB(2020a),and the problem is solved.Thanks for your's project again.

**Comment by jiang-jian-yu** [comment]
> Can you add a screenshot ?

I have met another problems when I set the fitness function.I have the same setting with toolbox-paremete-setting.png，but the error is fitnessfcn:not enough input arguments.
![2020_12_22_09_04 02](https://user-images.githubusercontent.com/71859920/102837850-ba096500-4437-11eb-8cdb-b0bea727fcf1.jpg)

**Comment by gyani-codes** [comment]
Hey sorry for the late repy. It's seems like pid_optim function is not in the current matalab environment, and I think you have not added the path of it in the matlab environment. Please do it .

**Comment by gyani-codes** [comment]
Follow the step 1 in the readme
